### ISSUE TITLE
when answering from lock screen the device should go back to the same state after the call is ended

### ISSUE THREAD

**Issue by fabriziomoscon** [hoxfon/react-native-twilio-programmable-voice#76]
RN 0.49
this lib 3.16.0
Android 8.0 One Plus 3
the app is running in the background and the screen is locked

Step to reproduce
Receive a phone call when the screen is locked (in my case a fingerprint lock is in place, not sure if that matters). After the call disconnects the app will still be opened in top of the lock screen. It is a suboptimal state because the user is let believe that the device is unlocked but in reality only the app is accessible.

**Comment by fabriziomoscon** [comment]
this should be fixed by version `3.18.0`

**Comment by SalmanMehmood** [comment]
This issue still exists in my app, when screen is locked and a call comes, after disconnecting the call, user can use the whole application while screen is locked.
ReactNative version: "react-native": "0.61.5",
"react-native-twilio-programmable-voice": "^3.21.3"

**Comment by fabriziomoscon** [comment]
@SalmanMehmood I am surprised that version 3 works with RN 0.61.5
Please check this PR #144 
which you can test by
`yarn add https://github.com/hoxfon/react-native-twilio-programmable-voice#android-twilio-v3`
